name: "newman_tests"
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest 
    container: 
      image: postman/newman
    steps: 
      - name: "checkout code"
        uses: actions/checkout@v2 
      - name: "run api tests" 
        run: newman run "Restful Booker BVT.postman_collection.json" -e "Production.postman_environment.json"

        #test